apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apr7-newgitopsdoc-6-app-tekton
  namespace: ai-rhdh
  finalizers: ["resources-finalizer.argocd.argoproj.io"]
spec:
  project: default
  source:
    path: ./components/apr7-newgitopsdoc-6/overlays/tekton
    repoURL: https://github.com/jdubrick-ai/apr7-newgitopsdoc-6-gitops.git
    targetRevision: main
  destination:
    namespace: rhdh-app
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: ai-rhdh
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
