apiVersion: batch/v1
kind: Job
metadata:
  name: dsp-clone-job-apr7-newgitopsdoc-6-gitops
spec:
  template:
    metadata:
      name: dsp-clone-job-apr7-newgitopsdoc-6-gitops
    spec:
      serviceAccountName: apr7-newgitopsdoc-6-dsp-job
      containers:
        - name: initialize-dsp
          image: quay.io/redhat-ai-dev/utils:latest
          command:
            - /bin/bash
            - -c
            - |
              NS=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
              oc wait -l statefulset=apr7-newgitopsdoc-6-notebook --for=condition=ready pod --timeout=300s
              oc exec  StatefulSet/apr7-newgitopsdoc-6-notebook -- git clone https://github.com/jdubrick-ai/apr7-newgitopsdoc-6
      restartPolicy: Never
